# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
#    - go mod tidy
#    - go mod vendor
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
    - GO111MODULE=on
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
  main: ./cmd/main.go
  binary: mdns
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - mips64
    - mips64le
    - mips
    - mipsle
  gomips:
    - hardfloat
    - softfloat
  ignore:
    - goos: darwin
      goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - tap:
      owner: OpenIoTHub
      name: homebrew-tap
    folder: Formula
    homepage:  https://github.com/IoTDevice/zeroconf
    description: mdns service finder
    test: |
      system "#{bin}/mdns -v"
scoop:
  bucket:
    owner: OpenIoTHub
    name: scoop-bucket
  homepage:  https://github.com/IoTDevice/zeroconf
  description: mdns service finder
  license: MIT
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    homepage:  https://github.com/IoTDevice/zeroconf
    description: mdns service finder
    maintainer: OpenIoTHub <newfarry@126.com>
    license: MIT
    vendor: mdns
    formats:
      - deb
      - rpm
    scripts:
      preinstall: "scripts/install_remove/preinstall.sh"
      postinstall: "scripts/install_remove/postinstall.sh"
      preremove: "scripts/install_remove/preremove.sh"
      postremove: "scripts/install_remove/postremove.sh"
snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}'
    summary: mdns service finder.
    name: mdns
    description: |
      mdns service finder
    grade: stable
#    confinement: classic
    publish: true
    apps:
      mdns:
        plugs: ["network", "network-bind"]
